live:
  - name: Arbitrum
    networks:
      - name: Mainnet
        chainid: 42161
        id: arbitrum-main-ogg123
        host: https://arb-mainnet.g.alchemy.com/v2/pa9ByTwpbQ2a14sQ5dMJSSUcS7U8XKiG
        explorer:  https://api.arbiscan.io/api
        multicall2: "0x80C7DD17B01855a6D2347444a0FCC36136a314de"

development:
  - name: Hardhat (Arbitrum Fork)
    id: hardhat-arbitrum-fork-3
    cmd: npx hardhat node
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      fork: arbitrum-main-ogg123